# Site settings
title: Pumpkin 
email: yananback@gmail.com
description: "博客网站测试"

logo_location: "./_favicon/site_log_32*32.png"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: pygments

#Other Global Configuration
exclude: ['README.md']
